name: CI Pipeline
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Dependencies
      run: npm install
    - name: Run Linter
      run: npm run lint
    - name: Check Formatting
      run: npm run prettier -- --check
    - name: Run Tests
      run: CI=true npm run test
    - name: Build Project
      run: npm run build
